### ISSUE TITLE
Non Production Logging form

### ISSUE THREAD

**Issue by TiberiusB** [Sensorica/VerdunNRP#1]
Non production Logging form seems to be broken. 
http://verdun.valnet.webfactional.com/accounting/unscheduled-time/

See how it looks in Sensorica's NRP. 

NOTE: need to be logged in to see the page. 
http://nrp.sensorica.co/accounting/unscheduled-time/ 

Wonder if it brakes because there is not enough data into the system... For example, Process patterns. I am going to create those and come back to it.

**Comment by TiberiusB** [comment]
In any case, if these list have 0 items, because we haven't put enough data into the system, they should still appear as lists that are initialized to a "--no items--" value for example.

**Comment by TiberiusB** [comment]
Played with Process Patterns and in the end I think that this is a bug. 
http://verdun.valnet.webfactional.com/admin/valueaccounting/processpattern/

**Comment by sqykly** [comment]
Yeah that's a botched JS implicit cast.  Fixing.

**Comment by bhaugen** [comment]
You're in good hands. I didn't know what a JS implicit cast was.

(Thanks again, David...)

**Comment by sqykly** [comment]
Done.  Note that it won't look exactly like the old version; this is intentional.  We're no longer putting form controls in table cells, but the table on that page is a best-practice HTML5 compliant table, so we keep it around for the convenience of the hearing-impaired's screen readers.  The controls have been moved to a modal that will pop up when you click the 'Edit' button for the row to be changed; this allows mobile users to manipulate the data without navigating the table (which is cumbersome on a small screen).

Don't thank me, the JS error was my mistake, Bob.  I was using the idiomatic (implicit) casts (`+string` becomes the string cast as a float, `0|string` becomes string as integer, `''+number` becomes number as string) and I accidentally typed `0+string` instead.  I shouldn't be using idioms like that anyway, it's just faster to type than `parseFloat`/`parseInt` etc.

Anyway, this and several other issues on that page are resolved.
