### ISSUE TITLE
Create Order dies

### ISSUE THREAD

**Issue by sqykly** [Sensorica/VerdunNRP#10]
On navigating Demand > Create Customer Order,

ImportError at /accounting/create-order/
No module named valueaccounting.tests.test_orders

**Comment by sqykly** [comment]
According to previous communications with Bob, the customer orders were never used and the tests never passed.  We need to decide whether we are implementing customer orders or not.  More accurately, @TiberiusB needs to decide.  This particular issue can be fixed easily and quickly, but that isn't going to fix whatever underlying issues exist.  I can either dig in and fix those, too, and have customer orders working, or disable the button and forget about it.  Up to you, @TiberiusB.

**Comment by bhaugen** [comment]
The tests did pass when they were initially written. Later changes broke the test, and as far as I knew (and I did ask at the time) nobody was using them. 

There's some complex code in there that does event-driven MRP, which I love, but that may also not be immediately useful and could be commented out and save some fixing.

**Comment by TiberiusB** [comment]
The Verdun project planning does have some kind of customer interactions.  
Case: During the first year we will roll our public events. The idea is to use these public events as a platform to get more funding. So we'll make calls to organizations out there to sponsor them, in exchange of some favors: ex. visibility for them through presence, publications, etc. Example, a local bank that offers financial services to startups might want to be visible during events where we treat about collaborative entrepreneurship. 
We can treat those as customers orders, and they will result in payments from these entities that will need to be recorded and have that money being allocated back into the process, pay people, buy equipment, pay bills. 
We will not use this NRP for entrepreneurial endeavors/projects where a product or a service is offered as the Mosquito project for example. So no customers like Robco or Michigan state University or people who would seek 3D modeling and printing services. All this will be managed in the Sensorica NRP, since Sensorica is moving to Verdun and will occupy the space of the first lab and continue its operations from there. We'll put all that commercial activity under Sensorica, not under Verdun. 
So we can say that the services that Verdun will offer is proportion for some organizations, during these public events. I can't think of other services now...

**Comment by sqykly** [comment]
@TiberiusB so we do need a working customer order interface, it just won't feature material goods?  As I understand it, the customer orders will then need to be fully functional and the products or services offered will be specified via facets, sponsorship project process patterns, etc.  Is this correct, or do we need a whole new UI for purchasing non-material goods?

**Comment by sqykly** [comment]
valnet #510 is now officially kicked here.  Two tests are still failing, but that's down from 4.

**Comment by sqykly** [comment]
@bhaugen @fosterlynn the remaining test failures are asserting that two commitments for the resource type `changeable` should exist after they make orders for `child` and `grandchild` resource types, and indeed there are none, but I don't see any other code in the test `setUp()` or objects_for_testing.py that would connect the `parent`/`child`/`grandchild` system defined in `objects_for_testing.Recipe` with the `changeable`/`another_changeable` system defined in `objects_for_testing.WorkFlowRecipe`.  Is it possible that `changeable` is supposed to be `parent`, `child`, or `grandchild`?  One or more of those have commitments such that the tests will pass in both cases (as far as I can tell)

**Comment by sqykly** [comment]
Having changed the tests that are labelled `workflow` to use the `WorkFlowRecipe` resource types, all tests pass.  And there was much rejoicing.
